export const CandidatesDataBacklog = [
  {
    id: "0",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Design"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "1",
    title: "Copywriting Content",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 8],
    tags: ["Research"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "2",
    image: "/src/assets/img/settingsBackground.png",
    title: "Update requiment list",
    subtitle: "Create content for peceland App",
    date: "Sep 20, 2021",
    multipleTask: undefined,
    tags: ["Planning"],
    attachments: 11,
    comments: undefined,
  },
  {
    id: "3",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: undefined,
    tags: ["Content"],
    attachments: undefined,
    comments: 8,
  },
  {
    id: "4",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Content", "Design"],
    attachments: undefined,
    comments: undefined,
  },
];
export const CandidatesDataTodo = [
  {
    id: "5",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Design"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "6",
    title: "Copywriting Content",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 8],
    tags: ["Research"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "7",
    image: "/src/assets/img/settingsBackground.png",
    title: "Update requiment list",
    subtitle: "Create content for peceland App",
    date: "Sep 20, 2021",
    multipleTask: undefined,
    tags: ["Planning"],
    attachments: 11,
    comments: undefined,
  },
  {
    id: "8",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: undefined,
    tags: ["Content"],
    attachments: undefined,
    comments: 8,
  },
  {
    id: "9",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Content", "Design"],
    attachments: undefined,
    comments: undefined,
  },
];
export const CandidatesDataInProgress = [
  {
    id: "10",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Design"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "11",
    title: "Copywriting Content",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 8],
    tags: ["Research"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "12",
    image: "/src/assets/img/settingsBackground.png",
    title: "Update requiment list",
    subtitle: "Create content for peceland App",
    date: "Sep 20, 2021",
    multipleTask: undefined,
    tags: ["Planning"],
    attachments: 11,
    comments: undefined,
  },
  {
    id: "13",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: undefined,
    tags: ["Content"],
    attachments: undefined,
    comments: 8,
  },
  {
    id: "14",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Content", "Design"],
    attachments: undefined,
    comments: undefined,
  },
];
export const CandidatesDataReview = [
  {
    id: "15",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Design"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "16",
    title: "Copywriting Content",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 8],
    tags: ["Research"],
    attachments: undefined,
    comments: undefined,
  },
  {
    id: "17",
    image: "/src/assets/img/settingsBackground.png",
    title: "Update requiment list",
    subtitle: "Create content for peceland App",
    date: "Sep 20, 2021",
    multipleTask: undefined,
    tags: ["Planning"],
    attachments: 11,
    comments: undefined,
  },
  {
    id: "18",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: undefined,
    tags: ["Content"],
    attachments: undefined,
    comments: 8,
  },
  {
    id: "19",
    image: "/src/assets/img/settingsBackground.png",
    title: "Create styleguide foundation",
    subtitle: "Create content for peceland App",
    date: "Aug 20, 2021",
    multipleTask: [0, 6],
    tags: ["Content", "Design"],
    attachments: undefined,
    comments: undefined,
  },
];

// export const CandidatesDataBacklog = [];
// export const CandidatesDataTodo = [];
// export const CandidatesDataInProgress = [];
// export const CandidatesDataReview = [];

export const columnsFromBackend = {
  backlog: {
    title: "Backlog",
    items: [],
  },
  to_do: {
    title: "To Do",
    items: [],
  },
  in_progress: {
    title: "In Progress",
    items: [],
  },
  in_review: {
    title: "Review",
    items: [],
  },
};
